# Generated by Django 2.1.3 on 2021-03-18 17:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergies_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GL', 'Glucose'), ('LT', 'Lactose'), ('EG', 'Eggs')], max_length=5), null=True, size=None),
        ),
    ]
